### ISSUE TITLE
Tuples for String format

### ISSUE THREAD

**Issue by nikolay** [zaphar/ucg#23]
It would be nice if able to use `template % tuple` with template having named properties from the tuple, which gives you the freedom to update the template independently. Using standard placeholder naming such as `${name}` would be great, too.

**Comment by zaphar** [comment]
Yeah it's true that the current template syntax is pretty rudimentary. I like the idea of using tuples with named properties but you would need a way to handle tuples. I'll have to give some thought to what the semantics should be for something like that.

**Comment by zaphar** [comment]
I'm leaning toward allowing full expressions in the `@{...}` portion of the template string since it's trivial to add. I've got a branch with the beginnings of the support for it. I'm going to experiment a little bit more before I merge it into mainline though.

**Comment by nikolay** [comment]
Why not use the standard Go template `{{ ... }}` vs having a `@` prefix?

**Comment by zaphar** [comment]
Continuity with the alternate substitution form. Using the @ symbol in both places is more consistent.

**Comment by zaphar** [comment]
I have merged this into main now.
