### ISSUE TITLE
Generating an entire k8s template file

### ISSUE THREAD

**Issue by frgomes** [zaphar/ucg#52]
I would like to generate an entire k8s template, made of services, stateful sets, pods, deployments, etc. At the moment, I'm generating separate yaml files and glueing them together outside ``ucg``.

Looking at the standard library, it's clear to me that such thing could be done inside ``ucg``, but the coin didn't drop yet in regards to the best practices for doing that.

What would be a good way for generating an entire template which could be consumed by ``kubectl`` ?

**Comment by zaphar** [comment]
Having only had one user I was aware of so far. (basically just me) I'm not sure there are any best practices for this at the moment. I could give better guidance with an example output you wanted to generate.

**Comment by frgomes** [comment]
Hello. I'm sorry for my long delay.

I'd like to avoid this kind of ugly bash script:

```bash
for ucgfile in *.ucg ;do
   echo "---" >> template.yaml
   ucg $ucgfile >> template.yaml
done
```
In other words, I would like to have the ability to write "---" followed by some yaml followed by "---" followed by some yaml and so on, using a single ucg file possibly or maybe several ucg files, but without having to resort to an ugly shell script glue.

**Comment by zaphar** [comment]
Ahh okay so the multi document syntax. There are a couple of ways this could be solved but I would probably need to add a feature or two to support it.

1. The convert expression can dump a value as yaml to a string. but I don't have a way to output the resulting value out as a raw string to a file so I'd need to add a facility to do that.

2. The arguably more valid way is to add multi document support to the yaml output in out expressions. I would have to give some thought as to how best to support the syntax there though. Perhaps a separate output target `yaml_multidoc` that always expects a list.

**Comment by zaphar** [comment]
new output target `yamlmulti` supports this feature now.
